# Generated by Django 3.0.3 on 2020-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_title', models.CharField(max_length=200)),
                ('device_code', models.CharField(max_length=200)),
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
