# Generated by Django 3.0.3 on 2020-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
