# Generated by Django 3.0.3 on 2020-02-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20200219_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='device_code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='device_id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='device_time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='device_title',
            new_name='Title',
        ),
    ]
